version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10 # Latest Python version (adjust if needed)
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install pandas matplotlib seaborn numpy squarify
      - run:
          name: Run Tests
          command: python test_graphs.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
    branches:
      only:
        - main # Run this workflow on the main branch only
